# Site settings
title: Sofware Engineering for Data Scientists
email: jakevdp -- AT -- uw.edu
description: "2016 UW course, Software Engineering for Data Scientists"
baseurl: "http://uwsoftwareengineering.github.io/"
url: "http://uwsoftwareengineering.github.io/"
twitter_username: uwescience
github_username:  uwsoftwareengineering


# Build settings
markdown: kramdown
